{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-drift.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "kube-drift.namespace" . }}
  labels:
    {{- include "kube-drift.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "kube-drift.selectorLabels" . | nindent 4 }}
{{- end }}
