{{- if and .Values.namespaceCreate .Values.namespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "kube-drift.labels" . | nindent 4 }}
{{- end }}
